linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif

linters:
  enable:
    - gofmt
    - gocritic
    - unconvert
    - goconst
    - gocyclo
    - misspell
    - unparam
    - golint
