repos:
-   repo: https://github.com/troian/pre-commit-golang
    rev: ab57c5db44bbeeae1031a2e9c2889367f8387d59
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
    -   id: go-imports
-   repo: https://github.com/syntaqx/git-hooks
    rev: f16f18866390cba642e8af6073ed59504aeada5c
    hooks:
    -   id: go-mod-tidy
