version: 2
jobs:
  integration:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: "./integrationTest.sh"
  unit:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go test ./...
  lint:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: "! go fmt ./... 2>&1 | read"
      - run: "! go vet ./... 2>&1 | read"
      - run: go get -u golang.org/x/lint/golint
      - run: "! golint ./... 2>&1 | read"
      - run: go get golang.org/x/tools/cmd/goimports
      - run: "! goimports ./... 2>&1 | read"
      - run: "! go mod tidy ./... 2>&1 | read"
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: ./buildAll.sh
      - run:
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(`cat VERSION`-`git rev-parse --short HEAD`)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/

workflows:
  version: 2
  build:
    jobs:
      - integration
      - unit
      - lint
      - publish-github-release
        requires:
          - integration
          - unit
          - lint
          filters:
        #      branches:
        #        only: master
