version: 2
jobs:
  integration:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: "./.circleci/init-env.sh > tests/env.sh"
      - run: "./integrationTest.sh"
  unit:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - go test ./...
workflows:
  version: 2
  build:
    jobs:
      - integration
      - unit