version: 2
jobs:
  integration:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: "./integrationTest.sh"
  unit:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go test ./...
  lint:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: "! go fmt ./... 2>&1 | read"
      - run: "! go vet ./... 2>&1 | read"
      - run: go get -u golang.org/x/lint/golint
      - run: "! golint ./... 2>&1 | read"
      - run: go get golang.org/x/tools/cmd/goimports
      - run: "! goimports ./... 2>&1 | read"
      - run: "! go mod tidy ./... 2>&1 | read"
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: "! golangci-lint 2>&1 | read" 
workflows:
  version: 2
  build:
    jobs:
      - integration
      - unit
      - lint
      
